# Generated by Django 4.2.2 on 2023-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_carrito_total_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_item',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
